version: '2'
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - '/docker/nginx-proxy/ssl:/etc/nginx/certs:ro'
      - '/docker/nginx-proxy/vhost.d:/etc/nginx/vhost.d'
      - '/docker/nginx-proxy/conf.d:/etc/nginx/conf.d'
      - '/docker/nginx-proxy/html:/usr/share/nginx/html'
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
  dockergen:
    image: jwilder/docker-gen
    container_name: dockergen
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx
    volumes:
      - '/docker/git_clone/rancher-init/nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro'
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.local
  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    environment:
       NGINX_DOCKER_GEN_CONTAINER:dockergen
    container_name: nginx-letsencrypt
    volumes_from:
      - nginx
    volumes:
      - '/docker/nginx-proxy/ssl:/etc/nginx/certs:rw'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'

networks:
  default:
    external:
      name: nginx-proxy
