version: '3'
services:
  nginx:
    image: nginx
    labels:
       - 'com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true'
       - 'com.example.nginx_proxy=true'
    ports:
      - 80:80
      - 443:443
    volumes:
      - /docker/nginx/conf.d:/etc/nginx/conf.d
      - /docker/nginx/vhost.d:/etc/nginx/vhost.d
      - /docker/nginx/html:/usr/share/nginx/html
      - /docker/nginx/certs:/etc/nginx/certs:ro

  nginx-gen:
    image: helder/docker-gen
    command: -notify "docker-label-sighup com.example.nginx_proxy" -watch -only-exposed -wait 10s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    restart: unless-stopped
    volumes:
      - /docker/nginx/conf.d:/etc/nginx/conf.d
      - /docker/nginx/vhost.d:/etc/nginx/vhost.d
      - /docker/nginx/html:/usr/share/nginx/html
      - /docker/nginx/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /docker/git_clone/rancher-init/nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: unless-stopped
    volumes:
      - /docker/nginx/conf.d:/etc/nginx/conf.d
      - /docker/nginx/vhost.d:/etc/nginx/vhost.d
      - /docker/nginx/html:/usr/share/nginx/html
      - /docker/nginx/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: nginx-gen
      NGINX_PROXY_CONTAINER: nginx-web

networks:
  default:
    external:
      name: ng-net
