db:
  image: mysql:5.7
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label_soft: io.blackcreeper.com.server=mysql
  volumes:
    - "/docker/wordpress/mysql:/var/lib/mysql"
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: wordpress
    MYSQL_DATABASE: wordpress
    MYSQL_USER: wordpress
    MYSQL_PASSWORD: wordpress
wordpress:
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label_soft: io.blackcreeper.com.server=wordpress
  image: wordpress:latest
  links:
    - 'db:'
  restart: always
  environment:
    WORDPRESS_DB_HOST: db:3306
    WORDPRESS_DB_PASSWORD: wordpress
    LETSENCRYPT_EMAIL: jacques@cretinon.fr
    LETSENCRYPT_HOST: wordpress.cretinon.fr
    VIRTUAL_HOST: wordpress.cretinon.fr
    VIRTUAL_PORT: '8090'
