version: '3.1'
 
services:
  wordpress:
    image: wordpress
    ports:
      - 8099:80
    networks:
      - wordpress-net
      - ng-net 
    environment:
      WORDPRESS_DB_HOST: wordpress_db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: db_parola
      VIRTUAL_HOST: wordpress.cretinon.fr
      VIRTUAL_PORT: 8099 
#      VIRTUAL_PROTO: https
      LETSENCRYPT_HOST: wordpress.cretinon.fr
      LETSENCRYPT_EMAIL: jacques@cretinon.fr

  wordpress_db:
    image: mariadb
    volumes:
      - /docker/wordpress/db_data:/var/lib/mysql
      - /docker/wordpress/html:/var/www/html
    networks:
      - wordpress-net
    environment:
      MYSQL_ROOT_PASSWORD: db_root_parola
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: db_parola
 
networks:
  wordpress-net:
      external: true
  ng-net:
      external: true
